name: macro_measure
description: "Allows users to figure out how much of a food they need to eat to hit a certain macro."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.x

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
